[package]
name = "kartoffel-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
kartoffel = { path = "../kartoffels/app/crates/kartoffel" }
# kartoffel = { path = "../kartoffels/backend/crates/kartoffel" }
threat-map = { path = "../threat-map" }